[TARGET_NODE]
ip = 127.0.0.1
rpc_port = 18286
p2p_port = 28286

[WALLET_RPC]
ip = 127.0.0.1
port = 18082
user = hb
password = 123456

[DAEMON_RPC]
ip = 127.0.0.1
port = 18081
trusted = true


[TRANSACTION]
;Please enter your wallet address.
recipient_address = abcdefghijklmnopqrstuvwxyz1234567890
amount_xmr = 0.0001
