[TARGET_NODE]
# ip = 82.157.60.174
ip = 127.0.0.1
rpc_port = 18285
p2p_port = 28285

[WALLET_RPC]
ip = 127.0.0.1
port = 18082
user = hb
password = 123456

[DAEMON_RPC]
# monerod 的 RPC 地址（wallet-rpc 构造交易时需要从这里拉取输出分布等链数据）
ip = 127.0.0.1
port = 18285

trusted = true

[TRANSACTION]
recipient_address = 9tiph89mgKDB1pSkBC3oMQ3svA9JmobbQZdEG5sBZxkHTBCHC9JH8CZXZg8QrQ5kweMaqMrCygjTwQ6ER3Dj14Z45vUs2B3
amount_xmr = 0.0001
